### ISSUE TITLE
Support Bartender 4 fade out bars

### ISSUE THREAD

**Issue by Desik** [mullerdavid/wow_CustomFlyout#1]
When using this in combination with Bartender 4 fade out bars (bars that are shown on mouse over/hidden on mouse leave)  the flyout buttons frame disappears, you can still click the invisible buttons but you can't see them. 

The expected behaviour will be to still show the flyout menu buttons when mouse-leaving the bartender button, as right now you can still click them but the icons and frame are not shown.

**Comment by mullerdavid** [comment]
Thanks for the report. I am not familiar with bartender. Is it a funcionality of the base addon? I am away from computer for a few days, i can probably look into it next weekend.
Is it this it? 
https://i.redd.it/30yamo70h0u21.png

**Comment by Desik** [comment]
> > Is it this it?
> https://i.redd.it/30yamo70h0u21.png

Yeah, thats the option.

**Comment by mullerdavid** [comment]
Workaround created that probably solves this.
