### ISSUE TITLE
Planning to release?

### ISSUE THREAD

**Issue by ghost** [mullerdavid/wow_CustomFlyout#3]
HI, I found your addon searching for classic/TBC flyout menu.  Would love something like this to organize my bars better.  I don't like that circle addon everyone seems to use.  But this would be perfect, are you planning to release it?  Thanks.

Also, I downloaded it and put it in my interface folder but can't seem to figure out how to create a flyout button.  Thanks.

**Comment by mullerdavid** [comment]
Hi, it is more or less released in it's current form at https://www.curseforge.com/wow/addons/customflyout , but I plan to add some basic gui to create the flyouts more user friendly. I just need some time, but P2 getting released soon doesn't really gives me this, so I don't know any ETA. If you have something specific in mind and stuck configuring it, I might be able to help, but it is basically creating and adding a macro with proper syntax and it would be processed.
You can also type /flyout and you will have some basic documentation (admittedly not user friendly). With the examples on curseforge (also see comments), it should be enough to get started.
