### ISSUE TITLE
Wrath Classic support

### ISSUE THREAD

**Issue by acusano** [mullerdavid/wow_CustomFlyout#5]
Greetings @mullerdavid!

With the pre-patch out for Wrath Classic, this awesome addon will require a few small updates to accomodate new additions to classes and items (for example, the macros for mage portals and teleports will need Dalaran added to the lists). Are any updates planned at this time?

**Comment by mullerdavid** [comment]
I totally forgot about it in prepatch preparation. I plan to update it whenever before wotlk release. If you have anything missing feel free to drop a list here.

**Comment by mullerdavid** [comment]
Should be included now, but couldn't test it yet.
